CREATE DATABASE IF NOT EXISTS science_park_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE science_park_db;

CREATE TABLE IF NOT EXISTS quote_enquiries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  school_name VARCHAR(200) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(150) DEFAULT NULL,
  city_state VARCHAR(150) NOT NULL,
  project_type VARCHAR(150) NOT NULL,
  interested_category VARCHAR(150) DEFAULT NULL,
  budget VARCHAR(100) DEFAULT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);